version: "3.9"
services:
  ai:
    build: ./ai
    ports: ["6000:6000"]
  backend:
    build: ./backend
    ports: ["8080:8080"]
    environment:
      - AI_BASE_URL=http://ai:6000
  frontend:
    build: ./frontend
    ports: ["3000:3000"]
